require("tweaks/beacons")
require("tweaks/tiles")
require("tweaks/intermediates")
require("tweaks/modules")
require("tweaks/tiles")
require("tweaks/teleportation")
require("tweaks/klonan_mods")
require("tweaks/spaceship")